name: Release Module

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Update module.json version
      run: |
        sed -i 's/"version": ".*"/"version": "${{ steps.get_version.outputs.VERSION }}"/' module.json

    - name: Create module zip
      run: |
        zip -r alternative-crit-damage.zip . -x "*.git*" "*.github*" "custom-crit-macro" "*.md" "*.zip"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        body: |
          ## Changes in v${{ steps.get_version.outputs.VERSION }}
          
          Enhanced alternative critical damage calculation with:
          - Advanced weapon parsing (deadly traits, persistent damage, splash damage)
          - Striking rune support
          - PF2e DamageRoll integration
          - Proper damage category formatting
          
          ### Installation
          Use this manifest URL in Foundry VTT's Module Manager:
          ```
          https://github.com/djpinger/pf2e-maximized-crit/releases/latest/download/module.json
          ```

    - name: Upload module.json
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./module.json
        asset_name: module.json
        asset_content_type: application/json

    - name: Upload module zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./alternative-crit-damage.zip
        asset_name: alternative-crit-damage.zip
        asset_content_type: application/zip